server:
  port: 9909

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: api_routes
        uri: http://127.0.0.1:7529
        predicates:
        - Path=/api/**